language: ruby
rvm:
  - 2.0.0
bundler_args: --without development:production
before_script:
  - psql -c 'create database organize_app_test;' -U postgres
  - cp config/database.yml.sample config/database.yml
script:
  - RAILS_ENV=test bundle exec rake db:migrate && bundle exec rspec
